""" Settings constants """
import pyglet

SETTINGS_DEFAULT_FULLSCREEN = True
SETTINGS_DEFAULT_WINDOW_STYLE = pyglet.window.Window.WINDOW_STYLE_DEFAULT
SETTINGS_DEFAULT_VSYNC = True
SETTINGS_DEFAULT_ANTIALIASING = 2
SETTINGS_DEFAULT_PARTICLES = 1.0
SETTINGS_DEFAULT_SHOW_LOGO = True
SETTINGS_DEFAULT_SHOW_FPS = False

SETTINGS_DEFAULT_SUBTITLE_ENABLED = False
SETTINGS_DEFAULT_SUBTITLE_SIZE = 18

# Default draw rate matches monitor refresh rate
SETTINGS_DEFAULT_UPDATE_RATE = 500
SETTINGS_DEFAULT_DRAW_RATE = SETTINGS_DEFAULT_UPDATE_RATE

SETTINGS_DEFAULT_VOLUME_SOUND = 70
SETTINGS_DEFAULT_VOLUME_MUSIC = 100
SETTINGS_DEFAULT_VOLUME_SPEECH = 100
SETTINGS_DEFAULT_VOLUME_MASTER = 100

SETTINGS_SIZE_MINIUM = (1280, 720)
SETTINGS_WINDOW_STYLE_CHOICES = (
    pyglet.window.Window.WINDOW_STYLE_DEFAULT,
    pyglet.window.Window.WINDOW_STYLE_DIALOG,
    pyglet.window.Window.WINDOW_STYLE_TOOL,
    pyglet.window.Window.WINDOW_STYLE_BORDERLESS,
    pyglet.window.Window.WINDOW_STYLE_TRANSPARENT,
    pyglet.window.Window.WINDOW_STYLE_OVERLAY
)
