""" Settings constants """

# Video settings
SETTINGS_DEFAULT_FULLSCREEN = True
SETTINGS_DEFAULT_VSYNC = True
SETTINGS_DEFAULT_ANTIALIASING = 4
SETTINGS_DEFAULT_PARTICLES = 1.0
SETTINGS_DEFAULT_SHOW_FPS = False
SETTINGS_DEFAULT_DEBUG = False
ANTIALIASING_VALUES = 0, 2, 4, 8, 16

# Default draw rate
SETTINGS_DEFAULT_DRAW_RATE = 60

# update rate
UPDATE_RATE = 9999

# fixed update rate
FIXED_RATE = 62

# Unlimited framerate
SETTINGS_UNLIMITED_DRAW_RATE = UPDATE_RATE

# FPS Limit options
SETTINGS_DRAW_RATES = [30, 60, 120, SETTINGS_UNLIMITED_DRAW_RATE]

# Minimum window size
SETTINGS_SIZE_MINIUM = (1280, 720)

# Audio driver
SETTINGS_DEFAULT_AUDIO_DRIVER = 'auto'

# Audio volumes
SETTINGS_DEFAULT_VOLUME_SOUND = 70
SETTINGS_DEFAULT_VOLUME_MUSIC = 100
SETTINGS_DEFAULT_VOLUME_SPEECH = 100
SETTINGS_DEFAULT_VOLUME_MASTER = 100

# Subtitles
SETTINGS_DEFAULT_SUBTITLE_ENABLED = False
SETTINGS_DEFAULT_SUBTITLE_SIZE = 18
